FROM node:23-alpine as development

# Working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=${DATABASE_USER}
ENV POSTGRES_PASSWORD=${DATABASE_PASSWORD}
ENV POSTGRES_DB=${DATABASE_NAME}
ENV PORT=${PORT}
# Install npm dependencies
RUN npm install

# Copy the application code
COPY . .

# Start the application
CMD ["npm", "run", "start:dev"]