services:
  app-dev:
    container_name: smean-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - smean-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smean-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_NAME}"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  smean-network:
    driver: bridge

volumes:
  postgres_data:  # Named volume for database persistence